### ISSUE TITLE
Cannot load simconnect.dll

### ISSUE THREAD

**Issue by Gamma36** [Fergo/fcdu-bugtracker#3]
Crash dump below. Looks like you need to rebuild as there may be a later version of .Net on my PC

regards
Paul

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.FlightSimulator.SimConnect.dll' or one of its dependencies. The specified module could not be found.
File name: 'Microsoft.FlightSimulator.SimConnect.dll'
   at 5B$0R'Q(6n'L9Pjf_yu5^#17\,.‌⁫‭‏‪‮‪⁬‎‭‏‮‭⁭⁭‏‍⁮‭⁫‍‎‮⁮‬‎‮⁬⁪‮⁬‏‬‬‏‎⁯‌⁫‫‮(Message& )
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
FergoCDU
    Assembly Version: 1.0.8246.35370
    Win32 Version: 1.0.8246.35370
    CodeBase: file:///C:/FergoCDU/fcdu_20220730_193909_8246_release/FergoCDU.exe
----------------------------------------
PathUZCxMBuanwvOYSavkiIyDZwQ
    Assembly Version: 0.0.0.0
    Win32 Version: 1.0.8246.35370
    CodeBase: file:///C:/FergoCDU/fcdu_20220730_193909_8246_release/FergoCDU.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Fleck
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/FergoCDU/fcdu_20220730_193909_8246_release/Fleck.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Gamma36** [comment]
![image](https://user-images.githubusercontent.com/14857816/183257074-f38850d4-a7d8-4a88-8769-b871738f4bd9.png)

**Comment by Gamma36** [comment]
The solution appears to be installing VC_redist.x64.exe and then rebooting.

Using Dependencies.exe Fleck.dll is the problem.

Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.32.31332

**Comment by Gamma36** [comment]
However, the CDU will not detect FS2020 on my home network. It is running with PMDG 737-600 loaded on the runway.

I'm a retired C++ developer, I think editing 737_Options.ini is too difficult for the average user. I suggest an installation program to run on the host sim, to enable network connections.

Whatever I do the app will not connect to FS2020 across my home network.

**Comment by Gamma36** [comment]
This message should not be displayed on the networked client (my laptop). It is fundamentally misleading as 737_Options.ini only exists on the server PC running FS2020 (a desktop PC)

![image](https://user-images.githubusercontent.com/14857816/183261291-0b181571-c9e0-48e5-ae79-d6c46522b557.png)

**Comment by Gamma36** [comment]
What is not clear is that the installation paragraph in the user guide does not explicitly say the product CANNOT be run on the client, for example a laptop. 

I suggest you modify the user guide to tell the user "Download the ZIP file to the PC that has FS2020 installed. Extract the zip file......etc"

I downloaded it to my laptop and it failed. You should check for an FS2020 install in FergoCDU.exe, to eliminate running on a network client. An installer (not unzip) could search for FS2020, if not found warn the user.
